#! /bin/csh -f
set machine_location=`hostname`
set fullhost=`nslookup $machine_location | grep -m 1 Name | awk '/Name:/{print $2}' | tr 'A-Z' 'a-z'`
if ("$fullhost" == "") then
  set fullhost=`nslookup ${machine_location}i | grep -m 1 Name | awk '/Name:/{print $2}' | tr 'A-Z' 'a-z'`
endif
if ("$fullhost" == "") then
  set fullhost=`hostname -f`
endif
# special handling of hostnames head*, node* that keeps mephi_check working
set mephi_check=`echo $machine_location | cut -c1-4`
if ("$mephi_check" == "head" || "$mephi_check" == "node") then
  switch ($fullhost)
  case "*.cm.cluster":
    breaksw
  default:
    echo "mephi_check = $mephi_check - special mephi cluster treatment applies"
    set machine_location="cluster21.mephi.ru"
    set fullhost=$machine_location
  endsw
endif
# special handling for ITER SDCC cluster nodes
set iter_check=`echo $machine_location | cut -d '.' -f 2-3`
if ("$iter_check" == "iter.org") then
  set fullhost=$machine_location
endif
# Assign location
switch ($fullhost)
case "*.iter.org":
  echo ITER
  breaksw
case "*.iaea.org":
  echo IAEA
  breaksw
case "*.iferc-csc.org":
  echo IFERC
  breaksw
case "*.eufus.eu":
case "*.efda-itm.eu":
case "*.marconi.cineca.it"
case "*.galileo.cineca.it"
  [ -d /afs ] && echo ITM || echo MARCONI
  breaksw
case "*.ipp-garching.mpg.de":
case "*.ipp.mpg.de":
case "*.rzg.mpg.de":
  echo IPP
  breaksw
case "*.mpcdf.mpg.de":
  echo MPCDF
  breaksw
case "*.ipp-hgw.mpg.de":
  echo IPP-HGW
  breaksw
case "*.fz-juelich.de":
case "*.ipp.kfa-juelich.de":
  echo FZJ
  breaksw
case "*.ccfe.ac.uk":
case "*.cumulus.hpc.l":
  echo CCFE
  breaksw
case "*.data.cluster":
  echo "CCFE-csd3"
  breaksw
case "*.jet.uk":
case "freia*.hpc.l":
  echo JET
  breaksw
case "*.mech.kuleuven.be":
case "*.icts.leuven.vsc":
case "*.hpc.kuleuven.be":
  set genius=`echo $fullhost | grep -i genius`
  if ("$genius" == "") then
    echo LEUVEN-WICE
  else
    echo LEUVEN
  endif
  breaksw
case "*.snellius.surf.nl":
case "*.bullx":
  echo SURFSARA
  breaksw
case "*.pppl.gov":
  echo PPPL
  breaksw
case "*.gat.com":
case "iris*.cluster":
case "saturn*.cluster":
  echo GA
  breaksw
case "*.wm.edu":
  echo WM
  breaksw
case "*.nersc.gov":
case "cori*":
  echo NERSC
  breaksw
case "*.ornl.gov":
case "jlore2025":
case "eos*":
case "fusion3":
case "ultrabucky*":
case "*bucky*":
  echo ORNL
  breaksw
case "*.ipp.cas.cn":
  echo ASIPP
  breaksw
case "*.nscc-hf.cn":
  echo NSCC
  breaksw
case "sms.hlsm.local":
  echo DLUT
  breaksw
case "*.swip.ac.cn":
case "mgmt":
  echo SWIP
  breaksw
case "*.ipr.res.in":
  echo IPR
  breaksw
case "iter-india.org":
case "*.iter-india.org":
  echo IN-DA
  breaksw
case "*.keio.ac.jp":
  echo KEIO
  breaksw
case "kraken01":
  echo KSTAR
  breaksw
case "*.spbstu.ru":
case "login1.cluster":
case "n01p*.cluster":
case "PLASMATHEORY08":
  echo SPBSTU
  breaksw
case "*.mephi.ru":
  echo MEPHI
  breaksw
case "*.uni-lj.si":
  echo UL
  breaksw
case "*.tok.ipp.cas.cz":
  echo "IPPCR"
  breaksw
case "*.cn":
case "*.hk":
case "*.mo":
  echo CN_UNKNOWN
  breaksw
case "*.eu":
case "*.an":
case "*.at":
case "*.aw":
case "*.ax":
case "*.be":
case "*.bg":
case "*.bl":
case "*.bq":
case "*.cw":
case "*.cy":
case "*.cz":
case "*.de":
case "*.dk":
case "*.ee":
case "*.es":
case "*.fi":
case "*.fo":
case "*.fr":
case "*.gf":
case "*.gp":
case "*.gr":
case "*.hr":
case "*.hu":
case "*.ie":
case "*.it":
case "*.lt":
case "*.lu":
case "*.lv":
case "*.mc":
case "*.mf":
case "*.mq":
case "*.mt":
case "*.nc":
case "*.nl":
case "*.pf":
case "*.pl":
case "*.pm":
case "*.pt":
case "*.re":
case "*.ro":
case "*.se":
case "*.si":
case "*.sk":
case "*.sx":
case "*.tf":
case "*.ua":
case "*.wf":
case "*.yt":
  echo EU_UNKNOWN
  breaksw
case "*.in":
  echo IN_UNKNOWN
  breaksw
case "*.jp":
  echo JP_UNKNOWN
  breaksw
case "*.kr":
  echo KR_UNKNOWN
  breaksw
case "*.rf":
case "*.ru":
case "*.su:"
  echo RF_UNKNOWN
  breaksw
case "*.gov":
case "*.edu":
case "*.as":
case "*.gu":
case "*.mp":
case "*.pr":
case "*.um":
case "*.us":
case "*.vi":
  echo USA_UNKNOWN
  breaksw
case "*.au":
case "*.cc":
case "*.cx":
case "*.hm":
case "*.nf":
  echo AU_UNKNOWN
  breaksw
case "*.ca":
  echo CA_UNKNOWN
  breaksw
case "*.kz":
  echo KZ_UNKNOWN
  breaksw
case "*.ac":
case "*.ai":
case "*.fk":
case "*.gb":
case "*.gg":
case "*.gi":
case "*.gs":
case "*.im":
case "*.io":
case "*.je":
case "*.pn":
case "*.sh":
case "*.uk":
case "*.vg":
  echo UK_UNKNOWN
  breaksw
case "*.ch":
  echo CH_UNKNOWN
  breaksw
default:
  echo UNKNOWN
endsw
